### ISSUE TITLE
Help Sciety know about changes to PREreviews

### ISSUE THREAD

**Issue by thewilkybarkid** [PREreview/prereview.org#1290]

**Comment by erkannt** [comment]
I've created a branch in the Sciety repo that makes it easier to test ingestion for a group on localhost.

https://github.com/sciety/sciety/compare/easier-localhost-ingestion-dev

On it you can use:
```
make ingestion-dev

# in another terminal:
make ingest-evaluations INGEST_ONLY=prereview INGEST_DEBUG=true
```

**Comment by thewilkybarkid** [comment]
Thanks @erkannt, looks to be working.
