### ISSUE TITLE
filtering and search features

### ISSUE THREAD

**Issue by mvuorre** [PREreview/prereview.org#1594]
Thanks for the great resource. Wondering if there is a roadmap/anticipated timeline for the "[filtering and search features](https://prereview.org/how-to-use)"?

**Comment by chadsansing** [comment]
Hi, @mvuorre! We are currently improving how the #request-a-review channel on our community Slack as a first step; after that, we'll start bringing recommendation and search back to PREreview.org itself, so, hopefully, we'll have more to share by the end of H1 2024.

**Comment by chadsansing** [comment]
If you have feedback you'd like to share with us about what might be most useful to you in that work, please don't hesitate to schedule a user research chat with me (chad@prereview.org) or to share your ideas on the #community-feedback channel of the Slack.
